fixe error
TypeError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/mount/src/mobile-price-prediction-using-machine-learning-algorithms-regression-/Mobile-Price-Prediction-Using-ML-Algorithms/app.py", line 222, in <module>
    st.success(f"Predicted Price: **PKR {int(price*3.17):,}**")
                                         ~~~^^^^^^^^^^^^